// ---------------------------------------------------------------------------
// Author: Labiyb M. Said — DevSecOps Engineer
// Contact: saidlabiybm@gmail.com
// ---------------------------------------------------------------------------

// sessions.go manages DB-backed login sessions.
//
// Unlike pipeline-init which used an in-memory map (lost on restart, not
// revocable), devportal sessions live in PostgreSQL so they:
//   - Survive pod restarts and rolling deployments
//   - Can be explicitly revoked by an admin (e.g. when a developer leaves)
//   - Are visible in the audit log
//
// Session lifecycle:
//   CreateSession  → called after successful OIDC/OAuth login
//   GetSession     → called on every authenticated HTTP request (via cookie)
//   TouchSession   → extends expires_at by 24h (sliding window)
//   DeleteSession  → called on logout
//   DeleteExpired  → called hourly by a background goroutine in main.go

package db

import (
	"context"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
)

// CreateSession inserts a new session row.
// The session ID is a crypto/rand 256-bit hex string generated by the auth
// package before calling this function — the DB does not generate it.
func (db *DB) CreateSession(ctx context.Context, s Session) error {
	const q = `
		INSERT INTO sessions (id, user_id, role, ip_address, user_agent, expires_at, last_seen)
		VALUES ($1, $2, $3, $4, $5, $6, now())
	`
	_, err := db.pool.Exec(ctx, q,
		s.ID, s.UserID, s.Role, s.IPAddress, s.UserAgent, s.ExpiresAt,
	)
	if err != nil {
		return fmt.Errorf("db.CreateSession: %w", err)
	}
	return nil
}

// GetSession returns the session with the given ID.
// Returns pgx.ErrNoRows when the session does not exist or has expired.
// The caller (auth middleware) must check ExpiresAt and call TouchSession
// to extend the window.
func (db *DB) GetSession(ctx context.Context, id string) (*Session, error) {
	// Filter expired sessions at query time so stale cookies are rejected
	// immediately even if the cleanup goroutine hasn't run yet.
	const q = `
		SELECT id, user_id, role, ip_address, user_agent, created_at, expires_at, last_seen
		FROM sessions
		WHERE id = $1
		  AND expires_at > now()
	`
	rows, err := db.pool.Query(ctx, q, id)
	if err != nil {
		return nil, fmt.Errorf("db.GetSession: query: %w", err)
	}
	session, err := pgx.CollectOneRow(rows, pgx.RowToAddrOfStructByName[Session])
	if err != nil {
		return nil, fmt.Errorf("db.GetSession: %w", err)
	}
	return session, nil
}

// TouchSession extends the session expiry by 24 hours and updates last_seen.
// Called on every authenticated request so active users never get logged out.
// We update last_seen and expires_at in a single query to avoid two round trips.
func (db *DB) TouchSession(ctx context.Context, id string) error {
	const q = `
		UPDATE sessions
		SET last_seen  = now(),
		    expires_at = now() + INTERVAL '24 hours'
		WHERE id = $1
		  AND expires_at > now()
	`
	tag, err := db.pool.Exec(ctx, q, id)
	if err != nil {
		return fmt.Errorf("db.TouchSession: %w", err)
	}
	// If no rows were updated the session has already expired.
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("db.TouchSession: session not found or expired")
	}
	return nil
}

// DeleteSession removes a session row on explicit logout.
// It is not an error if the session does not exist (idempotent).
func (db *DB) DeleteSession(ctx context.Context, id string) error {
	const q = `DELETE FROM sessions WHERE id = $1`
	_, err := db.pool.Exec(ctx, q, id)
	if err != nil {
		return fmt.Errorf("db.DeleteSession: %w", err)
	}
	return nil
}

// DeleteExpiredSessions removes all sessions whose expires_at is in the past.
// Called by a background goroutine in main.go once per hour so the table
// does not grow unbounded. Returns the number of rows deleted for logging.
func (db *DB) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	const q = `DELETE FROM sessions WHERE expires_at < $1`
	tag, err := db.pool.Exec(ctx, q, time.Now())
	if err != nil {
		return 0, fmt.Errorf("db.DeleteExpiredSessions: %w", err)
	}
	return tag.RowsAffected(), nil
}
