// ---------------------------------------------------------------------------
// Author: Labiyb M. Said — DevSecOps Engineer
// Contact: saidlabiybm@gmail.com
// ---------------------------------------------------------------------------

// helm.go generates an App-of-Apps Helm chart committed alongside the Kustomize
// file tree in the manifest repo. The chart lets platform engineers deploy an
// entire application stack to a new cluster with a single command:
//
//	helm install <app-slug> ./chart -n argocd
//
// The chart creates one ArgoCD Application per environment (dev/uat/prod),
// each pointing at the Kustomize overlay for that environment. When infra
// requirements exist (CNPG, Kafka, etc.) it also creates the companion
// -platform ArgoCD Applications.
//
// NOTE: Helm template syntax ( {{ }} ) conflicts with Go's text/template.
// These files are rendered via strings.NewReplacer — not renderFromTemplate —
// so Helm expressions are preserved verbatim in the committed files.
package template

import "strings"

// HelmChartInput holds the values needed to generate the App-of-Apps chart.
type HelmChartInput struct {
	AppName  string // service slug, e.g. "payment-service"
	RepoURL  string // manifest repo URL committed to values.yaml
	HasInfra bool   // when true, -platform ArgoCD Applications are also generated
}

// HelmChart returns the Helm chart file tree to commit to chart/ in the manifest repo.
// File paths are relative to the manifest repo root.
func HelmChart(input HelmChartInput) KustomizeFiles {
	hasInfra := "false"
	if input.HasInfra {
		hasInfra = "true"
	}
	r := strings.NewReplacer(
		"%%APP_SLUG%%", input.AppName,
		"%%REPO_URL%%", input.RepoURL,
		"%%HAS_INFRA%%", hasInfra,
	)
	return KustomizeFiles{
		"chart/Chart.yaml":                r.Replace(helmChartYAML),
		"chart/values.yaml":               r.Replace(helmValuesYAML),
		"chart/templates/_helpers.tpl":    r.Replace(helmHelpersTpl),
		"chart/templates/argocd-apps.yaml": r.Replace(helmArgoCDAppsYAML),
	}
}

// ── Chart file content ────────────────────────────────────────────────────────
// Placeholders: %%APP_SLUG%%, %%REPO_URL%%, %%HAS_INFRA%%
// Helm expressions ( {{ }} ) are preserved — not interpreted by Go templates.

const helmChartYAML = `apiVersion: v2
name: %%APP_SLUG%%
description: ArgoCD App-of-Apps package for %%APP_SLUG%% — NexBridge Technologies
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - argocd
  - app-of-apps
  - devportal
  - nexbridge
maintainers:
  - name: DevPortal
    url: https://devportal.nexbridge.io
# Generated by DevPortal — NexBridge Technologies
`

const helmValuesYAML = `# DevPortal-generated Helm chart for %%APP_SLUG%%
# Generated by NexBridge Technologies DevPortal
#
# Deploy all ArgoCD Applications for %%APP_SLUG%%:
#   helm install %%APP_SLUG%% ./chart -n argocd
#
# Upgrade after values change:
#   helm upgrade %%APP_SLUG%% ./chart -n argocd
#
# Dry-run first:
#   helm install %%APP_SLUG%% ./chart -n argocd --dry-run

repoURL: "%%REPO_URL%%"
argoNamespace: argocd
appSlug: %%APP_SLUG%%

environments:
  dev:
    enabled: true
    targetRevision: dev
    autoSync: true
    namespace: %%APP_SLUG%%-dev
  uat:
    enabled: true
    targetRevision: uat
    autoSync: true
    namespace: %%APP_SLUG%%-uat
  prod:
    enabled: true
    targetRevision: prod
    autoSync: false  # prod requires manual sync — set true to enable auto-sync
    namespace: %%APP_SLUG%%-prod

platform:
  enabled: %%HAS_INFRA%%
  autoSync: true
`

const helmHelpersTpl = `{{/*
NexBridge Technologies — DevPortal generated chart
Service: %%APP_SLUG%%

Helpers available:
  chart.fullname  — release name trimmed to 63 chars
  chart.labels    — common selector labels
*/}}

{{- define "chart.fullname" -}}
{{- printf "%s" .Release.Name | trunc 63 | trimSuffix "-" }}
{{- end }}

{{- define "chart.labels" -}}
app.kubernetes.io/name: {{ .Release.Name }}
app.kubernetes.io/managed-by: devportal
helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
{{- end }}
`

const helmArgoCDAppsYAML = `# ArgoCD Application-of-Applications for %%APP_SLUG%%
# Generated by DevPortal — NexBridge Technologies
#
# One Application per environment (dev / uat / prod) pointing at the
# Kustomize overlay for that environment. Platform Applications (operator
# CRs: CNPG, Kafka, RabbitMQ) are generated when platform.enabled=true.
---
{{- range $env, $cfg := .Values.environments }}
{{- if $cfg.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.appSlug }}-{{ $env }}
  namespace: {{ $.Values.argoNamespace }}
  labels:
    app.kubernetes.io/managed-by: devportal
    devportal.nexbridge.io/env: {{ $env }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ $.Values.repoURL }}
    path: {{ $.Values.appSlug }}/overlays/{{ $env }}
    targetRevision: {{ $cfg.targetRevision }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $cfg.namespace }}
  syncPolicy:
    {{- if $cfg.autoSync }}
    automated:
      prune: true
      selfHeal: true
    {{- end }}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}
{{- end }}
{{- if .Values.platform.enabled }}
{{- range $env, $cfg := .Values.environments }}
{{- if $cfg.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.appSlug }}-{{ $env }}-platform
  namespace: {{ $.Values.argoNamespace }}
  labels:
    app.kubernetes.io/managed-by: devportal
    devportal.nexbridge.io/env: {{ $env }}
    devportal.nexbridge.io/type: platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ $.Values.repoURL }}
    path: {{ $.Values.appSlug }}/infra/{{ $env }}
    targetRevision: {{ $cfg.targetRevision }}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    {{- if $.Values.platform.autoSync }}
    automated:
      prune: false
      selfHeal: true
    {{- end }}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}
{{- end }}
{{- end }}
`
